### ISSUE TITLE
Sample code doesn't run. TypeError: IPSWFirmware.__init__() got an unexpected keyword argument 'sha256sum'

### ISSUE THREAD

**Issue by ccarpiog** [Vislate/ipsw-me-python#1]
Hello!

I usually don't use Github and my coding skills are really lacking, so apologies in advance if this is not the right way of rising this issue.

I've tried to use ipsw-me but when I try to run your sample code I get an error on this line:

`device = api.device_info("iPad4,7")` 

This is the complete log:

`Traceback (most recent call last):`
`  File "~/updateIPSW/main.py", line 48, in <module>`
`    device = api.device_info("iPad4,7")`

`  File "~/pyenv/lib/python3.10/site-packages/ipsw_me/api.py", line 32, in device_info`
`    data['firmwares'] = [IPSWFirmware(**firmware) for firmware in data['firmwares']]`

`  File "~/pyenv/lib/python3.10/site-packages/ipsw_me/api.py", line 32, in <listcomp>`
`    data['firmwares'] = [IPSWFirmware(**firmware) for firmware in data['firmwares']]`

`TypeError: IPSWFirmware.__init__() got an unexpected keyword argument 'sha256sum'``

**Comment by Locvic** [comment]
Might be because the api for IPSW got updated and changed model. I’ll take
a look into this tonight thank you for letting me know!
